In [1]:
# Import my libraries

import numpy as np

In [7]:
my_random_array = np.random.randn(2, 3)
my_random_array

array([[ 0.20592626,  0.57483165, -0.24510709],
       [-0.11037057,  0.27165475, -0.82612591]])

In [8]:
np.arange(1, 5)  # from 1 inclusive to 5 exclusive

array([1, 2, 3, 4])

In [9]:
big_matrix = np.random.randn(10, 5)
big_matrix

array([[-0.97198877,  0.25594697, -1.08489201, -0.62649486, -0.27333828],
       [ 1.17002258, -0.60603538, -0.49632809,  0.99486657,  0.28029629],
       [-0.94917193,  0.32226357, -0.48738369, -1.64362464,  0.16976135],
       [ 1.16450792, -1.08788222,  1.16091119,  0.78629863, -0.34521322],
       [ 1.45322545, -0.99507212, -1.41638629,  0.54417589,  0.06854904],
       [-1.26661877,  0.64299607,  0.27389183,  0.10718068,  0.01128291],
       [-0.57736335,  1.06459504,  0.79036714,  1.88790416, -0.33866244],
       [-0.64720104,  0.37057678,  1.46194442, -0.16365545,  1.70842685],
       [-0.13953322,  1.01747057, -0.76163199, -0.37163054,  2.35542009],
       [ 1.78146592,  0.68087995, -0.14424296, -1.41845839,  1.16757703]])

In [10]:
big_matrix.ndim

2

In [11]:
big_matrix.shape

(10, 5)