In [12]:
# Import my libraries

import numpy as np

In [13]:
my_random_array = np.random.randn(2, 3)
my_random_array

array([[-0.11072041,  0.37787553, -0.28642118],
       [ 0.22975116,  0.74338383, -2.2086425 ]])

In [14]:
np.arange(1, 5)  # from 1 inclusive to 5 exclusive

array([1, 2, 3, 4])

In [15]:
big_matrix = np.random.randn(10, 5)
big_matrix

array([[ 0.43777758, -0.22576775, -0.70088482,  1.79195223,  0.07956797],
       [-1.95109289,  0.81672868, -0.38107285,  1.07732665, -0.8329521 ],
       [ 0.09282379, -2.03345732,  0.45096993,  0.71581006, -0.76844866],
       [ 0.18176383,  1.5182791 , -0.61272993, -2.81550497, -0.5301365 ],
       [ 0.43314992, -1.65841774, -1.04152858, -0.11919012, -0.54166882],
       [-0.37842448,  0.32952595, -0.57650188, -1.86008696, -0.8026311 ],
       [ 0.79997591, -1.32244218,  1.23847442, -0.94533294,  2.02638012],
       [-1.30889503,  0.46318386, -0.61014142,  1.47844869,  0.55971788],
       [-0.05051117,  1.14421392,  1.04745052,  0.33897823,  1.58235703],
       [ 0.394293  ,  0.33449727,  0.38185777,  2.10237987,  2.40687679]])

In [16]:
big_matrix.ndim

2

In [17]:
big_matrix.shape

(10, 5)

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[3]

3

In [20]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x[2:5] # Start on the third item, go up until the 6th item, exclusive.

array([2, 3, 4])